name: Build Action
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch
        type: string
        default: main
        required: true

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        check-latest: true
        node-version: lts/*
    - name: Install dependencies
      run: |
        npm i --ignore-scripts
    - name: Build Action
      run: |
        npm run build
    - name: Update dist
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add ./dist &&
        git commit -m "Update dist"
        git push origin HEAD:${{ inputs.ref }}
